name = "Hugo Fresh"
title = "Little Big Top Aerial"
license = "MIT"
licenselink = "https://github.com/StefMa/hugo-fresh/blob/master/LICENSE.md"
description = "A Hugo adaptation of the Fresh theme from CSS Ninja"
homepage = "https://github.com/StefMa/hugo-fresh"
tags = ["responsive", "one page", "light", "onepage", "company", "clean", "landing page"]
features = []
min_version = "0.45"
theme = "hugo-fresh"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.hero]
enabled = true
title = "Little Big Top"
subtitle = "Empowering Through Aerial Arts"
buttonText = "Join Our Mission"
buttonLink = "/about/"

[params.section1]
enabled = false

[params.section2]
enabled = false

[params.section3]
enabled = false

[params.section4]
enabled = false

[params.section5]
enabled = false

[params.footer]
enabled = true
content = "© 2025 Little Big Top, Inc. All rights reserved."