baseURL = "/"
title = "Little Big Top Aerial"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.hero]
enabled = true
title = "Little Big Top"
subtitle = "Empowering Through Aerial Arts"
buttonText = "Join Our Mission"
buttonLink = "/about/"

[params.section1]
enabled = false

[params.section2]
enabled = false

[params.section3]
enabled = false

[params.section4]
enabled = false

[params.section5]
enabled = false

[params.footer]
enabled = true
content = "© 2025 Little Big Top, Inc. All rights reserved."