baseURL = "/"
title = "Little Big Top Boise"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.hero]
enabled = true
title = ""
subtitle = "Empowering Youth Through Circus Arts"

# Enable footer
[params.footer]
enabled = true
content = "© 2025 Little Big Top Boise, Inc. All rights reserved."

# Add navbar links

[params.navbarlogo]
image = "logo.png"
link = "/"
width = 48  
height = 48

[[params.navbar]]
title = "About"
url = "/about/"

[[params.navbar]]
title = "Gallery"
url = "/gallery/"

[[params.navbar]]
title = "Contact"
url = "/contact/"

[[params.navbar]]
title = "Donate"
url = "/donate/"