baseURL = "/"
title = "Little Big Top Aerial"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.hero]
enabled = true
title = "Little Big Top"
subtitle = "Empowering Through Aerial Arts"

# Enable footer
[params.footer]
enabled = true
content = "© 2025 Little Big Top, Inc. All rights reserved."

# Add navbar links

[params.navbarlogo]
image = "logo.png"
link = "/"
width = 52
height = 52

[[params.navbar]]
title = "About"
url = "/about/"

[[params.navbar]]
title = "Events"
url = "/events/"

[[params.navbar]]
title = "Contact"
url = "/contact/"

[[params.navbar]]
title = "Donate"
url = "https://donate.example.com"